---
- hosts: all
  # connection: local
  gather_facts: true
  tasks:
    - name: run role
      include_role:
        name: bootstrap_k3os
    - name: reboot into k3os
      reboot:
        reboot_timeout: 3600

